import { Italiana , Inter} from "next/font/google";
import "./globals.css";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["200","400", "700"],
});

const italiana = Italiana({
  variable: "--font-italiana",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${italiana.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
